[listeners]
initialize = [
    "com.github.glassmc.example.client.v1_8_9.ExampleInitializeListener"
]
terminate = [
    "com.github.glassmc.example.client.v1_8_9.ExampleTerminateListener"
]

[dependencies]
client = "1.8.9"