namespace = "com.github.glassmc.example.client.v1_8_9"

[listeners]
initialize = [
    "ExampleInitializeListener"
]
terminate = [
    "ExampleTerminateListener"
]

[environment]
    [environment.has]
    client = "1.8.9"