implementations = [
    "1.7.10",
    "1.8.9",
    "1.17"
]

[listeners]
initialize = [
    "com.github.glassmc.example.client.ExampleClientInitializeListener"
]

[environment]
    [environment.has]
    client = "*"